apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave01
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-slave01
  template:
    metadata:
      labels:
        app: jenkins-slave01
    spec:
      containers:
        - name: jenkins
          image: sepehrimanian/jenkins-slave:v1.0.0
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
            - name: ssh
              containerPort: 22
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  nc -z localhost 22
                  exit $?
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  nc -z localhost 22
                  exit $?
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-slave01
        