version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JENKINS_URL: "http://103.75.196.148:8080/"
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "password123"
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - jenkins_home_data:/var/jenkins_home
      - docker_certs_client:/var/jenkins_home/.docker
    networks:
      - jenkins_network

  docker:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    volumes:
      - docker_data:/var/lib/docker
      - docker_certs:/certs
      - docker_certs_client:/certs/client
      - jenkins_home_data:/var/jenkins_home
    expose:
      - "2376"

volumes:
  jenkins_home_data:
  docker_data:
  docker_certs:
  docker_certs_client:
networks:
  jenkins_network:
    driver: bridge
