apiVersion: v1
kind: Secret
metadata:
  name: jenkins-credentials
  namespace: jenkins
type: Opaque
stringData:
  JENKINS_ADMIN_ID: "admin"
  JENKINS_ADMIN_PASSWORD: "password123"
  JENKINS_URL: "http://localhost:8080/"
  SSH_USERNAME: "root"
  SSH_PASSWORD: "root"