apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  # storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi