version: '3'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JENKINS_URL: "http://103.75.196.148:8080/"
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "password123"
    configs:
      - source: jenkins-cfg
        target: /var/jenkins_home/casc.yaml
    volumes:
      - jenkins_home_data_master:/var/jenkins_home
    networks:
      - jenkins_network
    depends_on:
      - jenkins-slave01
      - jenkins-slave02
    logging:
        driver: json-file
        options:
            max-file: '3'
            max-size: 100m

  jenkins-slave01:
    build:
      context: .
      dockerfile: Dockerfile.slave
    container_name: jenkins-slave01
    privileged: true
    environment:
        - JAVA_OPTS="-Dfile.encoding=UTF-8"
    volumes:
        - jenkins_home_data_salve01:/var/jenkins_home
    networks:
        - jenkins_network
    healthcheck:
        test: ["CMD-SHELL", "nc -v -w 10 -z 127.0.0.1 22"]
        interval: 10s
        timeout: 5s
        retries: 3
    logging:
        driver: json-file
        options:
            max-file: '3'
            max-size: 100m

  jenkins-slave02:
    build:
      context: .
      dockerfile: Dockerfile.slave
    container_name: jenkins-slave02
    privileged: true
    environment:
        - JAVA_OPTS="-Dfile.encoding=UTF-8"
    volumes:
        - jenkins_home_data_salve02:/var/jenkins_home
    networks:
        - jenkins_network
    healthcheck:
        test: ["CMD-SHELL", "nc -v -w 10 -z 127.0.0.1 22"]
        interval: 10s
        timeout: 5s
        retries: 3
    logging:
        driver: json-file
        options:
            max-file: '3'
            max-size: 100m

volumes:
  jenkins_home_data_master:
  jenkins_home_data_salve01:
  jenkins_home_data_salve02:

configs:
    jenkins-cfg:
        file: ./casc.yaml

networks:
  jenkins_network:
    driver: bridge
